// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kpfxdnvngsvckuubyhic.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtwZnhkbnZuZ3N2Y2t1dWJ5aGljIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwODYxNzEsImV4cCI6MjA1OTY2MjE3MX0.Y-OpwT8aUS4nu2KjVEDG9hPvNRVSjwmvIJRo7Zmpb-o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);